helmDefaults:
  tillerless: true
  atomic: false
  verify: false
  wait: true
  timeout: 1200

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: loki
  url: https://grafana.github.io/loki/charts

releases:
- name: grafana
  chart: stable/grafana
  version: 4.3.2
  namespace: grafana
  values:
  - "./config/grafana.yaml"

- name: prometheus
  chart: stable/prometheus
  version: 10.3.1
  namespace: prometheus
  values:
  - "./config/prometheus.yaml"

#- name: metrics-server
#  chart: stable/metrics-server
#  version: 2.9.0
#  namespace: metrics-server
#  values:
#  - "./config/metrics-server.yaml"
